### ISSUE TITLE
[BUG] Adding a new View in View Manager results in creating a PlayerView only

### ISSUE THREAD

**Issue by kz3r01n** [DroidlyMobileGames/SketchGDXPro#1] opened 2023-07-01 05:06 UTC
Every time I click the (+) button in the View Manager, the only thing created is a PlayerView that for some reason I can't edit the name.
![Screenshot_2023-07-01-13-03-09-76_779bb996b1c678e79483872163a48f91](https://github.com/DroidlyMobileGames/SketchGDXPro/assets/86095846/2eab756f-ab01-448c-b5a0-aaff2ac9bcbc)

**Comment by DroidlyMobileGames** [comment] 2023-07-01 12:41
Hey shoot thank you I forgot to upload the class for selecting the view types & the dialog my mistake I'm fixing this right as soon as I grab coffee!  Thanks for pointing this out!

**Comment by DroidlyMobileGames** [comment] 2023-07-01 16:20
The issue is now fixed update to the latest version I am still working on a way to automatically add Gameview Game Loader but for now you need to manually add it if you want to add Screens.  New I took longer because I was fixing this option coming soon how to guides as well!

**Closed as completed** 2023-07-01 16:37 UTC
